#!/bin/bash
# Script to help check Blender console output

echo "=========================================="
echo "Blender Console Check Helper"
echo "=========================================="
echo ""
echo "Method 1: Run Blender from Terminal"
echo "-----------------------------------"
echo "1. Open Terminal"
echo "2. Run one of these commands:"
echo ""
echo "   # If Blender is in Applications:"
echo "   /Applications/Blender.app/Contents/MacOS/Blender"
echo ""
echo "   # Or find your Blender installation:"
echo "   find /Applications -name Blender.app 2>/dev/null"
echo ""
echo "Method 2: Use Blender's Built-in Console"
echo "----------------------------------------"
echo "1. Open Blender"
echo "2. Go to: Window → Toggle System Console"
echo "   (Or press Cmd+Shift+C)"
echo ""
echo "What to Look For:"
echo "-----------------"
echo "When the addon loads, you should see:"
echo "  - 'BlenderMCP: Modular system loaded successfully'"
echo "  - 'BlenderMCP: Calling register_all_handlers()...'"
echo "  - 'BlenderMCP: Registered X handlers'"
echo "  - 'BlenderMCP: ✓ Render handlers registered'"
echo "  - 'BlenderMCP: ✓ Sketchfab handlers registered'"
echo ""
echo "If you see errors, copy them and share them."
echo "=========================================="
